{"name": "Verify VPC Spoke behaviours", "status": "broken", "statusDetails": {"message": "google.api_core.exceptions.Conflict: 409 POST https://compute.googleapis.com/compute/v1/projects/lab-tenant/global/networks: The resource 'projects/lab-tenant/global/networks/my-vpc-spoke-test' already exists\n", "trace": "  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/vpc_spoke_steps.py\", line 74, in step_create_vpc_network_in_remote_project\n    insert_vpc = network_client.insert(\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/cloud/compute_v1/services/networks/client.py\", line 1693, in insert\n    response = rpc(\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py\", line 131, in __call__\n    return wrapped_func(*args, **kwargs)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py\", line 76, in error_remapped_callable\n    return callable_(*args, **kwargs)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/cloud/compute_v1/services/networks/transports/rest.py\", line 1529, in __call__\n    raise core_exceptions.from_http_response(response)\n"}, "steps": [{"name": "Given I have a GCP project \"lab-hybrid-connectivity\"", "status": "passed", "start": 1744021399583, "stop": 1744021401622}, {"name": "And there is an NCC hub \"se-us-ncc-hub\" deployed within it", "status": "passed", "start": 1744021401622, "stop": 1744021402421}, {"name": "And the \"default\" connectivity group auto-accept list contains \"lab-tenant\"", "status": "passed", "start": 1744021402422, "stop": 1744021402980}, {"name": "When I create a VPC network \"my-vpc-spoke-test\" in project \"lab-tenant\"", "status": "broken", "statusDetails": {"message": "google.api_core.exceptions.Conflict: 409 POST https://compute.googleapis.com/compute/v1/projects/lab-tenant/global/networks: The resource 'projects/lab-tenant/global/networks/my-vpc-spoke-test' already exists\n", "trace": "  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/vpc_spoke_steps.py\", line 74, in step_create_vpc_network_in_remote_project\n    insert_vpc = network_client.insert(\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/cloud/compute_v1/services/networks/client.py\", line 1693, in insert\n    response = rpc(\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py\", line 131, in __call__\n    return wrapped_func(*args, **kwargs)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py\", line 76, in error_remapped_callable\n    return callable_(*args, **kwargs)\n  File \"/Users/jameskelly/Desktop/behave/.venv/lib/python3.9/site-packages/google/cloud/compute_v1/services/networks/transports/rest.py\", line 1529, in __call__\n    raise core_exceptions.from_http_response(response)\n"}, "start": 1744021402980, "stop": 1744021405120}, {"name": "And add a subnet \"my-vpc-spoke-subnet\" to the VPC with cidr \"10.0.4.0/24\" in \"us-south1\"", "status": "skipped", "start": 1744021405123, "stop": 1744021405123}, {"name": "And I attach the VPC as a VPC spoke with name \"my-test-vpc-spoke\" to the NCC hub", "status": "skipped", "start": 1744021405123, "stop": 1744021405123}, {"name": "Then the VPC spoke should be in an \"ACTIVE\" state", "status": "skipped", "start": 1744021405123, "stop": 1744021405123}, {"name": "And the NCC hub route table should contain a route for the VPC spoke", "status": "skipped", "start": 1744021405123, "stop": 1744021405123}], "start": 1744021399582, "stop": 1744021405123, "uuid": "cf1a4c09-b2d0-4658-9887-fabf0380802b", "historyId": "2fbeef6647745a7b82131be7ec44d766", "fullName": "GCP Network Connectivity Center VPC Spoke Validation: Verify VPC Spoke behaviours", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "GCP Network Connectivity Center VPC Spoke Validation"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}